#pragma once
//macros used in project (names abbreviations on the end)
//dimensions of main application structure's windows and buttons are responsive to dimentions of some main parts pointed by /*M*/

/*GENERAL*/
#define TRUE 1
#define FALSE 0
#define MAX_FILE_PATH_LENGTH 50
#define MAX_ANIMAL_NAME_LENGTH 20
/*MAIN WINDOW*/
/*M*/#define MAIN_WINDOW_WIDTH 960
/*M*/#define MAIN_WINDOW_HEIGHT 540
/*STATIC WINDOWS*/ // static means here that type of content in the window doesn't change, however the items in this content can change (e.g. statistics window is always in the left top corner, but single stats in this window can change)
/*M*/#define STATS_WINDOW_WIDTH 400
/*M*/#define STATS_WINDOW_HEIGHT 140
#define STATS_WINDOW_TLCX 0
#define STATS_WINDOW_TLCY 0
#define STATS_WINDOW_RGBA_COLOR 178, 223, 219, 255 //26, 188, 156
/*M*/#define NEEDS_BARS_WINDOW_WIDTH 480
#define NEEDS_BARS_WINDOW_HEIGHT STATS_WINDOW_HEIGHT
#define NEEDS_BARS_WINDOW_TLCX STATS_WINDOW_WIDTH
#define NEEDS_BARS_WINDOW_TLCY 0
#define NEEDS_BARS_WINDOW_RGBA_COLOR 178, 235, 242, 255
#define TEXT_EVENTS_WINDOW_WIDTH MAIN_WINDOW_WIDTH
#define TEXT_EVENTS_WINDOW_HEIGHT (MAIN_WINDOW_HEIGHT - STATS_WINDOW_HEIGHT - ACTIVE_WINDOW_HEIGHT)
#define TEXT_EVENTS_WINDOW_TLCX 0
#define TEXT_EVENTS_WINDOW_TLCY (MAIN_WINDOW_HEIGHT - TEXT_EVENTS_WINDOW_HEIGHT)
#define TEXT_EVENTS_WINDOW_RGBA_COLOR 255, 204, 188, 255 // 192, 57, 43
/*CHARACTER / SHOP / GAME / FOOD / DRINK WINDOW*/
/*M*/#define	ACTIVE_WINDOW_WIDTH 800
/*M*/#define ACTIVE_WINDOW_HEIGHT 280
#define ACTIVE_WINDOW_TLCX (MAIN_WINDOW_WIDTH - ACTIVE_WINDOW_WIDTH)
#define ACTIVE_WINDOW_TLCY STATS_WINDOW_HEIGHT
#define ROOM_IMG_PATH "media/room.png"
/*STATIC BUTTONS*/
#define SHOP_B_WIDTH (MAIN_WINDOW_WIDTH - ACTIVE_WINDOW_WIDTH)
#define SHOP_B_HEIGHT (ACTIVE_WINDOW_HEIGHT/2)
#define SHOP_B_TLCX 0
#define SHOP_B_TLCY ACTIVE_WINDOW_TLCY
#define SHOP_B_LEFT_TEXT_PADDING 50
#define SHOP_B_TOP_TEXT_PADDING 50
#define GAMES_B_WIDTH SHOP_B_WIDTH
#define GAMES_B_HEIGHT SHOP_B_HEIGHT
#define GAMES_B_TLCX 0
#define GAMES_B_TLCY (SHOP_B_TLCY + SHOP_B_HEIGHT)
#define GAMES_B_LEFT_TEXT_PADDING 40
#define GAMES_B_TOP_TEXT_PADDING 50
#define EXIT_B_WIDTH (MAIN_WINDOW_WIDTH - STATS_WINDOW_WIDTH - NEEDS_BARS_WINDOW_WIDTH)
#define EXIT_B_HEIGHT (STATS_WINDOW_HEIGHT/2)
#define EXIT_B_TLCX (MAIN_WINDOW_WIDTH - EXIT_B_WIDTH)
#define EXIT_B_TLCY 0
#define EXIT_B_LEFT_TEXT_PADDING 15
#define EXIT_B_TOP_TEXT_PADDING 20
#define SAVE_B_WIDTH EXIT_B_WIDTH
#define SAVE_B_HEIGHT (STATS_WINDOW_HEIGHT/2)
#define SAVE_B_TLCX EXIT_B_TLCX
#define SAVE_B_TLCY EXIT_B_HEIGHT
#define SAVE_B_LEFT_TEXT_PADDING 5
#define SAVE_B_TOP_TEXT_PADDING 20
#define DEFAULT_B_RGBA_COLOR_INACTIVE 236, 240, 241, 255
#define DEFAULT_B_RGBA_COLOR_HIGHLIGHTED 149, 165, 166, 255
#define DEFAULT_B_RGBA_COLOR_ACTIVE 52, 73, 94, 255
/*NEEDS BARS AND BARS*/
#define EXP_BAR_WIDTH 200
#define EXP_BAR_HEIGHT 20
#define NEED_BAR_WIDTH 200
#define NEED_BAR_HEIGHT 20
#define BAR_TEXT_SPACE_HEIGHT 20
#define NEED_BARS_PADDING_FROM_TOP 40 // ~ height of space for "needs bars" text
#define NEED_BAR_BOTTOM_PADDING 10 // bottom padding of every bar 
#define NEED_BAR_SIDE_PADDING 20 // left and right padding of every bar 
#define BAR_BORDER_RGBA_COLOR 0, 0, 0, 255
#define NEED_BAR_RGBA_COLOR_EMPTY 255, 255, 255, 255
#define NEED_BAR_RGBA_COLOR_PERFECT 0, 204, 0, 255 
#define NEED_BAR_RGBA_COLOR_GOOD 0, 245, 0, 255 
#define NEED_BAR_RGBA_COLOR_NORMAL 205, 220, 57, 255
#define NEED_BAR_RGBA_COLOR_WARNING 255, 128, 0, 255
#define NEED_BAR_RGBA_COLOR_DANGER 255, 69, 0, 255
#define HUNGER_BAR_TEXT_TLCX (NEEDS_BARS_WINDOW_TLCX + NEED_BAR_SIDE_PADDING)
#define HUNGER_BAR_TEXT_TLCY (NEEDS_BARS_WINDOW_TLCY + NEED_BARS_PADDING_FROM_TOP)
#define THIRST_BAR_TEXT_TLCX HUNGER_BAR_TEXT_TLCX
#define THIRST_BAR_TEXT_TLCY (HUNGER_BAR_TEXT_TLCY + NEED_BAR_HEIGHT + NEED_BAR_BOTTOM_PADDING + BAR_TEXT_SPACE_HEIGHT)
#define ENERGY_BAR_TEXT_TLCX (HUNGER_BAR_TEXT_TLCX + NEED_BAR_WIDTH + (2*NEED_BAR_SIDE_PADDING))
#define ENERGY_BAR_TEXT_TLCY HUNGER_BAR_TEXT_TLCY
#define FUN_BAR_TEXT_TLCX ENERGY_BAR_TEXT_TLCX
#define FUN_BAR_TEXT_TLCY THIRST_BAR_TEXT_TLCY
#define MAX_BAR_VALUES_TEXT_SIZE 12 // xxxxx/yyyyy\n
/*USABLE OBJECTS*/
#define DEFAULT_OBJECT_RELATED_TO_NEED_MIN_USE_EFFECT 5
#define DEFAULT_OBJECT_RELATED_TO_NEED_MAX_USE_EFFECT 10
#define DEFAULT_OBJECT_NOT_RELATED_TO_NEED_MIN_USE_EFFECT 0
#define DEFAULT_OBJECT_NOT_RELATED_TO_NEED_MAX_USE_EFFECT -5
#define DEFAULT_STARTING_MIN_LVL_UP_PRICE
#define DEFAULT_STARTING_MAX_LVL_UP_PRICE
#define	DEFAULT_LVL_UP_PRICE 
#define DEFAULT_LVL_UP_BONUS 10
#define DEFAULT_EVERY_FIVE_LEVELS_BONUS 1
/*FONTS*/
#define DEFAULT_FONT_NAME "funnypages.ttf"
#define TEXT_EVENTS_FONT "OpenSans-Regular.ttf"
#define TEXT_EVENTS_FONT_SIZE 16
#define BUTTONS_FONT_SIZE 24
#define DEFAULT_FONT_SIZE 13
/*CHARACTER (DEFAULT) WINDOW VIEW*/
#define SLEEP_B_TLCX ACTIVE_WINDOW_TLCX + 380
#define SLEEP_B_TLCY ACTIVE_WINDOW_TLCY + 14
#define FOOD_B_TLCX ACTIVE_WINDOW_TLCX + 460
#define FOOD_B_TLCY ACTIVE_WINDOW_TLCY + 112
#define DRINKS_B_TLCX FOOD_B_TLCX + 160
#define DRINKS_B_TLCY FOOD_B_TLCY
#define TOY_B_TLCX ACTIVE_WINDOW_TLCX + 20
#define TOY_B_TLCY ACTIVE_WINDOW_TLCY + 170
/*STATS WINDOW VIEW*/
#define MAX_ANIMAL_LVL 99
#define MAX_LVL_TEXT_SIZE 8 // "LVL: xx\n" = 8 chars
#define MAX_MONEY_AMOUNT_TEXT_SIZE 10 // max amount: "999999999\n" 
#define MAX_MONEY_AMOUNT (unsigned long)999999999 // unsigned long can handle numbers to 4,294,967,295, so 999,999,999 is my choice to max amount of money
#define COIN_TEXTURE_PATH "media/coin.png"
#define DOGE_IMG_PATH "media/doge.png" // [PRE]
/*TEXT EVENTS*/
#define MAX_EVENT_MESSAGE_LENGTH 110 //number is set so that text can't reach the end of text event window
#define MAX_NUMBER_OF_EVENTS 6 // [PRE]
/*
	names abbreviations:
b - button
TLC - top left corner


*/